export const API_URL = 'http://localhost:5000'
export const FETCHING_DATA = 'EVENT_FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'EVENT_FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'EVENT_FETCHING_DATA_FAILURE'